use serde::{Deserialize, Serialize};

use crate::entities::currency as entities;
use crate::entities::currency::CurrencyKind;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")] 
pub struct Currency {
    pub id: i32,
    pub symbol: String,
    pub name: String,
    pub kind: String,
    pub is_active: bool,
    pub precision: i16,
}

impl From<entities::Currency> for Currency {
    fn from(entity: entities::Currency) -> Self {
        Currency {
            id: entity.id,
            symbol: entity.symbol,
            name: entity.name,
            kind: entity.kind.into(), // This line works because of `impl From<CurrencyKind> for String` block
            is_active: entity.is_active,
            precision: entity.precision,
        }
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")] 
pub struct CreateRequest {
    pub symbol: String,
    pub name: String,
    pub kind: String,
    pub is_active: bool,
    pub precision: i16,
}

impl CreateRequest {
    pub fn to_entity(self) -> Result<entities::Currency, String> {
        Ok(entities::Currency {
            id: 0, // ID will be generated by the database
            symbol: self.symbol,
            name: self.name,
            kind: CurrencyKind::from_string(&self.kind)?,
            is_active: self.is_active,
            precision: self.precision,
        })
    }
}


#[derive(Serialize)]
#[serde(rename_all = "camelCase")] 
pub struct CreateResponse {
    pub new_id: i32,
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")] 
pub struct UpdateRequest {
    pub id: i32,
    pub symbol: String,
    pub name: String,
    pub kind: String,
    pub is_active: bool,
    pub precision: i16,
}

impl UpdateRequest {
    pub fn to_entity(self) -> Result<entities::Currency, String> {
        Ok(entities::Currency {
            id: self.id,
            symbol: self.symbol,
            name: self.name,
            kind: CurrencyKind::from_string(&self.kind)?,
            is_active: self.is_active,
            precision: self.precision,
        })
    }
}